In [44]:
import torch
from torch.nn import Linear,ReLU
from torch.autograd import Variable
from torch import nn,optim

In [12]:
inp = Variable(torch.randn(1,10))
myLayer = Linear(in_features = 10,out_features=5,bias=True)
myLayer(inp)

tensor([[ 1.4548,  0.3707, -0.1673, -1.0712,  0.6192]],
       grad_fn=<AddmmBackward>)

In [14]:
myLayer.weight

Parameter containing:
tensor([[ 0.0681, -0.0344, -0.2693, -0.3010, -0.1081, -0.2733, -0.1857,  0.2880,
          0.1790,  0.1960],
        [ 0.2622,  0.2642,  0.0325,  0.1749,  0.2346, -0.1603,  0.2290, -0.3026,
          0.1582,  0.2224],
        [-0.1712, -0.1016,  0.2152,  0.1162,  0.0006, -0.3022, -0.3122, -0.2024,
         -0.1931,  0.3020],
        [-0.2767,  0.1383, -0.2369,  0.3077,  0.0331,  0.2216,  0.0341,  0.2364,
          0.0250, -0.2715],
        [ 0.2893,  0.0312, -0.2853, -0.1750,  0.2115, -0.2576,  0.1813, -0.3025,
         -0.2089, -0.1537]], requires_grad=True)

In [15]:
myLayer.bias

Parameter containing:
tensor([ 0.0732, -0.1720, -0.1039, -0.0781, -0.1436], requires_grad=True)

In [16]:
myLayer1 = Linear(10,5)
myLayer2 = Linear(5,2)
myLayer2(myLayer1(inp))

tensor([[0.5349, 0.7195]], grad_fn=<AddmmBackward>)

In [23]:
sample_data = Variable(torch.Tensor([1,2,-1,-1]))
myRelu = ReLU()
myRelu(sample_data)

tensor([1., 2., 0., 0.])

In [26]:
#使用pytorch构建深度学习算法

class MyFirstNetwork(nn.Module):
    def __init__(self,input_size,hidden_size,output_size):
        super(MyFirstNetwork,self).__init__()
        self.layer1 = Linear(input_size,hidden_size)
        self.layer2 = Linear(hidden_size,output_size)
    def __forward__(self,input):
        out = self.layer1(input)
        out = nn.ReLU(out)
        out = self.layer2(out)
        return out

In [28]:
loss = nn.MSELoss()
input = Variable(torch.randn(3,5),requires_grad=True)
target = Variable(torch.randn(3,5))
output = loss(input,target)
output.backward()

In [32]:
def cross_entropy(true_label,prediction):
    if true_label == 1:
        return -log(prediction)
    else:
        return -log(1-prediction)

In [33]:
loss = nn.CrossEntropyLoss()
input = Variable(torch.randn(3,5),requires_grad=True)
target = Variable(torch.LongTensor(3).random_(5))
output = loss(input,target)
output.backward()

In [34]:
output

tensor(1.5481, grad_fn=<NllLossBackward>)

In [43]:
optimizer = optim.SGD(model.parameters(), lr = 0.01)
for input, target in dataset:
    optimizer.zero_grad()
    output = model(input)
    loss = loss_fn(output, target)
    loss.backward()
    optimizer.step()

NameError: name 'model' is not defined